### ISSUE TITLE
Installation issues with V3.6.94

### ISSUE THREAD

**Issue by jwstemper** [madskristensen/ImageOptimizer#28]
### Installed product versions
- Visual Studio: 2015 Pro V14.0.25431.01 Update3
- Image Optomizer V3.6.94

### Description
Trying to install VSIX and getting an error "This file is not a valid VSIX package"
Additionally when installing thru Nuget it seems to be installing but after restarting VS I'm prompted again to install Image Optimizer. This continues as many times as I care to try.

### Steps to recreate
1. Download
2. Install

**Comment by jwstemper** [comment]
Getting this error in the log file (downloaded the file three times and still got the error): 

 11/28/2016 11:21:28 AM - Initializing Install...
11/28/2016 11:21:29 AM - System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.GetVsixType(Stream vsixStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by madskristensen** [comment]
Fixed
