### ISSUE TITLE
Some .gif images crash ImageOptimizer

### ISSUE THREAD

**Issue by hraud** [madskristensen/ImageOptimizer#7]
Upgraded to ImageOptimizer 3.0.15.  Seems to work fine on .png and .jpg images.  But when it tries to optimize some of my .gif images, it crashes with Event ID 1026.  Some .gif images are optimized ok, so it's only certain .gif images that have this problem.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
Stack:
   at System.IO.File.Copy(System.String, System.String, Boolean)
   at MadsKristensen.ImageOptimizer.ImageOptimizerPackage.HandleResult(MadsKristensen.ImageOptimizer.CompressionResult, Int32)
   at MadsKristensen.ImageOptimizer.ImageOptimizerPackage+<>c__DisplayClass3.<OptimizeImage>b__2(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by madskristensen** [comment]
You can get the latest nightly here http://vsixgallery.com/extension/bf95754f-93d3-42ff-bfe3-e05d23188b08/ in a few minute when it's done building on the CI server. It should fix the issue.

Thanks for reporting the issue!
